### ISSUE TITLE
python setup.py test は非推奨になっているのでpytestに置き換え

### ISSUE THREAD

**Issue by kashewnuts** [beproud/bpnotify#16]
#15 で合わせて対応しようとしたが、pytestに変更時にテスト結果が変わってしまい時間がかかりそうだったのでIssueとして切り出した。

refs:
* 該当PR: #17 
* [setup\.py は非推奨になりましたか？ \- Python Packaging User Guide](https://packaging.python.org/ja/latest/discussions/setup-py-deprecated/)

**Comment by shimizukawa** [comment]
対応しかけのPRがあれば、誰かが（誰？）見てくれるかも？

**Comment by kashewnuts** [comment]
本文を更新して該当PRを追記しました 🙏

**Comment by kashewnuts** [comment]
setuptools v72でついに削除されたので、次回リリース時は注意 https://github.com/pypa/setuptools/issues/4519

**Comment by kashewnuts** [comment]
v72が取り下げられ、v72.1.0がリリースされたので一旦収まったが将来的に対応は必要になりそう https://github.com/pypa/setuptools/issues/4519

**Comment by kashewnuts** [comment]
#17 で対応したのでClose
